### ISSUE TITLE
Production experience?

### ISSUE THREAD

**Issue by aehlke** [SYSTRAN/fuzzy-match#54]
Hi, this looks very promising for a project where we would run this on iOS/macOS wrapped in Swift, and also compiled to wasm for web.

Are there any production experiences with this to share, or demos / products which integrate it that we could try out? How does it compare with the popular "fzf" algorithm for instance, or other popular fuzzy match tools? Thank you.

**Comment by guillaumekln** [comment]
Hi,

This projet was initially developped for this research paper: https://aclanthology.org/2020.acl-main.144. As far as I know there are no comparisons with other algorithms and no public demos or products using this project directly.
